export const CHANGE_ISAUTHENICATION = "CHANGE_ISAUTHENICATION"

export const CHANGE_SIGN_UP_EMAIL = "CHANGE_SIGN_UP_EMAIL"
export const CHANGE_SIGN_UP_PASSWORD = "CHANGE_SIGN_UP_PASSWORD"
export const CHANGE_SIGN_UP_MESSAGE = "CHANGE_SIGN_UP_MESSAGE"
export const CHANGE_SIGN_UP_NAME = "CHANGE_SIGN_UP_NAME"

export const CHANGE_SIGN_IN_MESSAGE = "CHANGE_SIGN_IN_MESSAGE"
export const CHANGE_SIGN_IN_EMAIL = "CHANGE_SIGN_IN_EMAIL"
export const CHANGE_SIGN_IN_PASSWORD = "CHANGE_SIGN_IN_PASSWORD"

export const CHANGE_USERS = "CHANGE_USERS"
export const CHANGE_RANKS_AND_FACE = "CHANGE_RANKS_AND_FACE"

export const CHANGE_IMAGE_URL = "CHANGE_IMAGE_URL"
export const CHANGE_BACKGROUND = "CHANGE_BACKGROUND"
export const CHANGE_FACES = "CHANGE_FACES"
export const CHANGE_FACE_BOX = "CHANGE_FACE_BOX"
export const CHANGE_WELCOME_STATUS = "CHANGE_WELCOME_STATUS"
export const CHANGE_ALREADY_STATUS = "CHANGE_ALREADY_STATUS"

